/* EduSpace live-data style: School Profile and Top Availability use only configured authoritative records; no bundled school or vacancy fallback is rendered. */

import { useState } from "react";
import { ArrowLeft, Heart, X, FileText, CircleGauge, ChevronDown, BookOpen } from "lucide-react";
import { useLocation } from "wouter";
import { AppFrame, AppTopBar } from "@/components/eduspace/Chrome";
import { DataNotice, SchoolThumb } from "@/components/eduspace/UI";
import { useEduSpaceData } from "@/contexts/DataContext";
import { getEligibleSchools } from "@/data/source";
import type { School } from "@/data/eduspace";

export function SchoolProfilePage() {
  const [, navigate] = useLocation();
  const { status, data, reload } = useEduSpaceData();
  const id = window.location.pathname.split("/").pop()?.split("?")[0] || "";
  const school = data?.schools.find((item) => item.id === id);
  const savedKey = `eduspace-saved-${id}`;
  const [saved, setSaved] = useState(() => window.localStorage.getItem(savedKey) === "true");
  const [tab, setTab] = useState("Overview");
  const [hostelOpen, setHostelOpen] = useState(() => new URLSearchParams(window.location.search).get("hostel") === "1");
  const toggleSaved = () => setSaved((current) => { const next = !current; window.localStorage.setItem(savedKey, String(next)); return next; });
  if (status !== "ready" || !data || !school) return <AppFrame className="school-profile-screen"><AppTopBar title="School Profile" onBack={() => window.history.back()} /><DataNotice onRetry={reload} title={status === "loading" ? "Loading school" : "School unavailable"} copy={status === "loading" ? "Fetching the latest school record." : "This school is not present in the configured data source."} /></AppFrame>;
  return <AppFrame className="school-profile-screen"><AppTopBar title="School Profile" onBack={() => window.history.back()} /><div className="school-profile-body"><div className="school-hero"><img src={school.image} alt={`Classroom at ${school.name}`} /><span className="hero-label">{school.type.toUpperCase()}</span><button className={`hero-heart ${saved ? "saved" : ""}`} onClick={toggleSaved} aria-label={saved ? "Remove from saved" : "Save school"}><Heart size={17} fill={saved ? "currentColor" : "none"} /></button></div><h2>{school.name}</h2><p className="school-location"><span>⌖</span> {school.region} · {school.location}</p><div className="school-stat-grid"><button className="school-stat available" onClick={() => navigate(`/availability?school=${school.id}`)}><span>SPACES AVAILABLE</span><strong>{school.spaces}</strong><em>Check Seat Details →</em></button><button className="school-stat hostel" onClick={() => setHostelOpen(true)}><span>BOARDING STATUS</span><strong>{school.boarding}</strong><em>View Hostel Stats →</em></button></div><div className="school-tabs">{["Overview", "Academics"].map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>{tab === "Overview" ? <div className="school-copy"><h3>About the School</h3><p>{school.description}</p><h3>Our Mission</h3><p>To build young minds.</p><h3>Historical Profile</h3><p>The Best of the Best.</p></div> : <div className="academics-copy"><div><CircleGauge size={16} /><span><strong>{school.category} education</strong><small>Current school programme</small></span></div><div><FileText size={16} /><span><strong>Curriculum</strong><small>National curriculum</small></span></div></div>}</div>{hostelOpen && <HostelSheet school={school} onClose={() => setHostelOpen(false)} />}</AppFrame>;
}

function HostelSheet({ school, onClose }: { school: School; onClose: () => void }) {
  const capacity = Math.max(school.spaces, 0);
  return <div className="sheet-layer" role="dialog" aria-modal="true" aria-labelledby="hostel-title"><button className="sheet-scrim" aria-label="Close hostel statistics" onClick={onClose} /><section className="hostel-sheet"><div className="sheet-heading"><h2 id="hostel-title">Hostel Statistics</h2><button onClick={onClose} aria-label="Close"><X size={16} /></button></div><div className="hostel-card boys"><strong>Boys Hostel</strong><div><span><small>Capacity</small><b>{capacity}</b></span><span><small>Enrolled</small><b>{capacity}</b></span><span><small>Available</small><b className="green">0</b></span></div></div><div className="hostel-card girls"><strong>Girls Hostel</strong><div><span><small>Capacity</small><b>{capacity}</b></span><span><small>Enrolled</small><b>{capacity}</b></span><span><small>Available</small><b className="green">0</b></span></div></div><button className="primary-button" onClick={onClose}>Close</button></section></div>;
}

export function AvailabilityPage() {
  const [, navigate] = useLocation();
  const { status, data, reload } = useEduSpaceData();
  const [expanded, setExpanded] = useState<string | null>(() => new URLSearchParams(window.location.search).get("grade") || null);
  if (status !== "ready" || !data) return <AppFrame className="availability-screen"><AppTopBar title="Availability" onBack={() => window.history.back()} /><DataNotice onRetry={reload} title={status === "loading" ? "Loading availability" : "Live availability unavailable"} copy={status === "loading" ? "Fetching current eligible schools." : "Configure VITE_EDUSPACE_DATA_URL to display eligible schools from the authoritative source."} /></AppFrame>;
  const eligibleSchools = getEligibleSchools(data);
  return <AppFrame className="availability-screen"><AppTopBar title="Availability" onBack={() => window.history.back()} /><div className="availability-body"><section className="allocation-card"><p>PLACEMENT SEAT ALLOCATION</p><div className="allocation-ring"><div><strong>{eligibleSchools.reduce((sum, school) => sum + school.spaces, 0)}</strong><small>SPACES LEFT</small><em>{eligibleSchools.length} eligible schools</em></div></div></section><div className="availability-summary"><div><strong>{data.schools.length}</strong><small>ALL SCHOOLS</small></div><div><strong>{eligibleSchools.length}</strong><small>ELIGIBLE</small></div><div><strong className="mint-text">{eligibleSchools.reduce((sum, school) => sum + school.spaces, 0)}</strong><small>AVAILABLE</small></div></div><section className="eligible-schools"><h2>Top Availability</h2>{eligibleSchools.length ? eligibleSchools.map((school, index) => <button className="eligible-school-row" key={school.id} onClick={() => navigate(`/school/${school.id}`)}><span className="eligible-rank">{index + 1}</span><SchoolThumb src={school.image} alt="" /><span className="eligible-school-copy"><strong>{school.name}</strong><small>{school.region} · {school.location}</small><em>{school.spaces} spaces available</em></span><span className="list-chevron">›</span></button>) : <DataNotice title="No eligible schools" copy="The live source returned no schools with available spaces." />}</section><section className="vacancies"><h2><BookOpen size={12} /> Grade Vacancies Breakdown</h2>{data.vacancyRows.map((row) => <div className={`vacancy-row ${expanded === row.grade ? "expanded" : ""}`} key={row.grade}><button className="vacancy-head" onClick={() => setExpanded(expanded === row.grade ? null : row.grade)}><div><strong>{row.grade}</strong><small>{row.note}</small></div><span><em>{row.enrolled} spaces</em><ChevronDown size={12} /></span></button><div className="vacancy-progress"><i style={{ width: `${row.occupied}%` }} /></div><div className="vacancy-foot"><span>{row.enrolled} Enrolled</span><span>{row.occupied}% Occupied</span></div>{expanded === row.grade && <div className="stream-list">{row.streams.map((stream) => <div key={stream.name}><span><strong>{stream.name}</strong><small>{stream.capacity} seat capacity</small></span><span>{stream.enrolled} / {stream.capacity} Enrolled ({Math.round((stream.enrolled / stream.capacity) * 100)}%)</span></div>)}</div>}</div>)}</section></div></AppFrame>;
}
